# spring configuration
spring:
   application:
      name: emaillist
   profiles:
      active: development
      
      
---
# common spring boot configuration
spring:
   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
   web:
      resources:
         static-locations: classpath:/assets/

   thymeleaf:
      prefix : classpath:templates/
      check-template-location: true
      mode: HTML5
      suffix : .html
      cache : false

mybatis:
   config-location: classpath:mybatis/configuration.xml

logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO



---
# development profile: spring boot configuration
spring:
   config:
      activate:
         on-profile: development

   devtools:
      livereload:
         enabled: true
                     
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.172:3307/webdb?charset=utf8
      username: webdb
      password: webdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
   
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: utf-8
         enabled: true
         


---
# production profile: spring boot configuration
spring:
   config:
      activate:
         on-profile: production

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.175:3307/webdb?charset=utf8
      username: webdb
      password: webdb123
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
         
server:
   port: 8088
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true